enabled=true
filename_desktop=
filename_documents=Documents
filename_download=Downloads
filename_music=Music
filename_pictures=Pictures
filename_publicshare=Public
filename_templates=Templates
filename_videos=Videos
filename_projects=Projects
