bin_path = "/home/shadhin/.local/bin/yt-dlp-trim.sh"
download_folder = "/home/shadhin/Downloads"
save_window_position = false

[window_position]
x = 0.0
y = 0.0

[options]
video_resolution = "FullHD"
video_format = "Mp4"
audio_quality = "Best"
audio_format = "Mp3"
