primary={{ primary.hex }}
on_primary={{ on_primary.hex }}
secondary={{ secondary.hex }}
tertiary={{ tertiary.hex }}
error={{ error.hex }}
background={{ background.hex }}
on_background={{ on_background.hex }}
surface={{ surface.hex }}
on_surface={{ on_surface.hex }}
surface_variant={{ surface_variant.hex }}
on_surface_variant={{ on_surface_variant.hex }}
outline={{ outline.hex }}
surface_container={{ surface_container.hex }}
